git:
  filters:
  - filter_type: file
    file_format: STRUCTURED_JSON
    source_file: Source_File/apple.json
    source_language: en
    translation_files_expression: '<lang>/example_structured_json.json'
