-git:
  filters:
    - filter_type: file
      file_format: STRUCTURED_JSON
      source_language: en
      source_file: Source_File/apple.json
      # path expression to translation files, must contain <lang> placeholder
      translation_files_expression: '<lang>/example_structured_json.json'
